### ISSUE TITLE
Doggo Hats

### ISSUE THREAD

**Issue by aoeixsz4** [NullCGT/SpliceHack#106]
Heya. I didn't want to make a pull request just yet, raised this issue to discuss.
Patch currently is tiny, it does appear to work but more thorough testing is needed.
Plus I want to hear your thoughts on the implementation details and how that might affect gameplay.
a) Only allowing doggos to wear hats is perhaps unfair to kitties.
b) Tame doggos will only put on non-cursed hats but other doggos will pick up and put on any hats, 
    including cursed ones (might play test this quickly)...
c) Leaning towards 'a'pply the hats but then I gotta check how the apply code for saddle works,
    and figure out where to draw the line before allowing the player to apply just about any amusing piece
    of clothing to a tame animal.
See also the commit of the patch on my fork of your code: [31ff53f3d](https://github.com/aoeixsz4/SpliceHack/commit/31ff53f3de367e5a72cffd7cec2ffb49db5c95e3)

**Comment by copperwater** [comment]
But in Splice, while zombies still grudge living pets, they have neither a disease bite nor an intelligence-draining bite, and so there's nothing a hat would particularly protect against. The only variants where this patch makes sense are GruntHack and EvilHack.

**Comment by aoeixsz4** [comment]
Well yeah, perhaps so. But K2 refused and AntiGulp seemed keen, so let's see :P 
more play testing shows that in its current, simplistic form, doggos will remove hats and put on better ones.
This is the expected behaviour for the bit of intelligent monster code I allowed them to access,
but it is perhaps pushing it a tad too far :D 
screenshot: https://imgur.com/a/c0foFeH

**Comment by aoeixsz4** [comment]
Correction. With this patch non-tame dogs will not put on hats. They could put them on if they did,
but I think the code for them being interested in picking up things is all tied to apport and tameness,
and wild dogs simply aren't interested in picking thing sup.

**Comment by NullCGT** [comment]
Closing out for now. Doggo hat discussion may continue, however.
