### ISSUE TITLE
Inappropriate Carnivorism and Silver-Hating

### ISSUE THREAD

**Issue by Arlnoff** [NullCGT/SpliceHack#108]
My friend and I have so far confirmed that both merfolk and angels are obligate carnivores (can't eat food rations, for example) and are silver-hating (get seared by weapons was confirmed for angels, can't put on silver items confirmed for merfolk). This seems... inappropriate. Are they inheriting Ghoul attributes by accident? This is in version 0.8, for Windows.

Edit: further confirmed that Ghouls _can_ eat food rations and veggie corpses, but still properly trigger the "corpse is too fresh!" message for non-veggie corpses

**Comment by NullCGT** [comment]
Resolved by the new build of 0.8.0!
