### ISSUE TITLE
Pet getting stuck

### ISSUE THREAD

**Issue by Arlnoff** [NullCGT/SpliceHack#112]
Windows, 0.8. I've encountered this twice now- my pet will follow me into a shop and get stuck at the threshold square just inside the door. I can't swap places with them. Doesn't happen consistently, will update if I figure out the trigger, I'm vaguely suspicious that it's a picked up item

**Comment by copperwater** [comment]
This is the same issue as https://github.com/NetHack/NetHack/issues/329, and will be fixed the next time SpliceHack merges in vanilla.

**Comment by NullCGT** [comment]
Copperwater is correct. The fix for vanilla just went live yesterday, so it has not been pulled in yet. The next time SpliceHack releases, this issue should be fixed.
