### ISSUE TITLE
Object weight is not updated when material changes

### ISSUE THREAD

**Issue by Neko-chan448** [NullCGT/SpliceHack#116]
https://github.com/NullCGT/SpliceHack/blob/fdeef6c222637246a87c649b0fc059aec3e6de13/src/mkobj.c#L3441

I believe weight() needs to be called at some point here because otherwise the weight of the object will not change. e.g. I made shadowspun plate mail with a transmuter, and the weight is the normal 450, except when it's in a bag of holding

 https://github.com/NullCGT/SpliceHack/blob/fdeef6c222637246a87c649b0fc059aec3e6de13/src/mkobj.c#L1525 <--- here is weight()

**Comment by NullCGT** [comment]
Fixed on the development branch. Will close this issue when the fix is merged into master.
