### ISSUE TITLE
Faulty checks for infernal starting inventory.

### ISSUE THREAD

**Issue by KarlMHanson** [NullCGT/SpliceHack#120]
Infernal wizards can start with both rings of fire resistance and regeneration.

The code (in u_init.c) seems to intend to check for rings of regeneration and silver items, but uses Role_if(PM_INFERNAL) instead of Race_if(PM_INFERNAL), which seems like an error. It seems like fire resistance isn't checked at all.

**Comment by NullCGT** [comment]
Good catch! I would be surprised if this was the only bug of this kind in the code.

Junethack has been keeping me busy, but I should be able to set aside a bit of time to fix this.
