### ISSUE TITLE
Falling from grace prevents entry into Black Market

### ISSUE THREAD

**Issue by SilverSpirit** [NullCGT/SpliceHack#132]
One-eyed Sam blocks the entrance and pleasantly greets me, but does not let me pass. Playing │Unix SpliceHack Version 0.8.2-2 Work-in-progress - last build Mon Dec 21 (dbdfe5f58b8d8c781c5a237b3b0f5a5c36796bed,branch:Master).

**Comment by NullCGT** [comment]
Closed out, since angels have not been added yet in Spl-R-1.0.0.
