### ISSUE TITLE
Program in disorder!

### ISSUE THREAD

**Issue by SilverSpirit** [NullCGT/SpliceHack#133]
![image](https://user-images.githubusercontent.com/16724061/107110904-8c2a8500-6819-11eb-8ed8-2e94854731cf.png)
. Playing Unix SpliceHack Version 0.8.2-2 Work-in-progress - last build Mon Dec 21 (dbdfe5f,branch:Master).

**Comment by NullCGT** [comment]
This bug was due to vampire consumption, and is fixed in Spl-R-1.0.0.
