### ISSUE TITLE
Forging stuff

### ISSUE THREAD

**Issue by RojjaCebolla** [NullCGT/SpliceHack#146]
1. items with no charges output items with no charges, see https://imgur.com/wUE5nwP.png
2. ~~the "base" item is mostly erased, but the second item's material goes through (same screenshot)~~ it is maybe unclear to the user that this will happen?
3. forging any two items, like an apple and a carrot, deletes the second item but not the first
4. ~~even invalid forge attempts delete the forge~~ currently, only "imbuing" deletes the forge!

fixed 3 and 4 in https://github.com/NullCGT/SpliceHack/tree/bugfixesForge;
i feel like the more general fix might be to make the end steps of [doforging line 762 through 779](https://github.com/NullCGT/SpliceHack/blob/6217b1c1c985733019c14ced046ae4fb7a57266d/src/fountain.c#L762) more conditional?

**Comment by NullCGT** [comment]
Material from the second item carrying over to the first is one hundred percent intentional.

**Comment by RikerW** [comment]
Suggestion for forging combos:
- tooled horn + wand of fire = horn of fire
- tooled horn + wand of cold = horn of frost
- sack + can of grease = oilskin sack (are oilskin sacks even particularly good, or at least better than a can of grease for your helmet/cloak?)
- leather drum + scroll of earth = drum of earthquake

weirder ones i thought up:
- katana + twohanded sword = tsurugi
- low boots/high boots + ring of levitation = levitation boots
- amulet of change + amulet of lifesaving = amulet of reincarnation
- amulet of reincarnation + ring of polymorph control = amulet of lifesaving
- amulet of guarding + plain cloak = cloak of protection

**Comment by RikerW** [comment]
Important bug: you can destroy unique items easily, making your game unwinnable with a typo, since there's 
1. no check for unique items for either obj 
2. no check for what happens if you made an invalid combination, and obj2 is always used up, so RIP my poor amulet of yendor (newt imbued)

**Comment by RikerW** [comment]
Bugs I mentioned above as well as all bugs in the original post fixed in #157.

**Comment by RojjaCebolla** [comment]
At present, because the forge isn't used up, I don't think forge recipes should result in big upgrades. Kes, riker - do you think forges should maybe be consumed some of the time when doing regular recipes? I'm concerned about someone say, improving a bunch of the loot in Ludios using just one forge, to the point where it approaches a low-grade polypile.

Other than that quibble, I'm into the idea of massively expanding recipes!  It's a cool way players can acquire stuff they want beyond the existing systems of "hope the item drops" and "wish for the item, but only if it's as good or better than a magic marker".

**Comment by RikerW** [comment]
I'd prefer to not have the strong upgrades rather than making the forge vanish sometime. It would suck to accidentally vanish your only forge since you didn't realize, or to overall limit your mundane combos.
