### ISSUE TITLE
Food Poisoning occurs far too frequently.

### ISSUE THREAD

**Issue by NullCGT** [NullCGT/SpliceHack#147]
Eating a corpse that is only a few turns old seems to result in food poisoning. I have a hunch that this was caused when merging the moldy corpses patch, but I'm not sure what exactly the root cause is.

**Comment by Doesnty** [comment]
Fairly confident it's variable _aged_ being uninitialized in make_corpse() (mon.c) that's doing it, although I had the reverse issue from it; corpses were dated to turn 80 million something so pets would eagerly snack on zombie corpses.

**Comment by copperwater** [comment]
Does this present in xNetHack as well? I haven't seen any such reports with respect to moldy corpses.

**Comment by RojjaCebolla** [comment]
> Does this present in xNetHack as well? I haven't seen any such reports with respect to moldy corpses.

i think the bug cropped up from fuzzer-centric fixes, not the moldy patch!
