### ISSUE TITLE
Small bug/missing feature with Elbereth conduct

### ISSUE THREAD

**Issue by k21971** [NullCGT/SpliceHack#16]
Noticed that when the player checks #conduct, it will show that they haven't engraved Elbereth if they haven't yet (good). On a successful engrave, issuing #conduct again shows nothing about engraving Elbereth, even though the commit for it clearly shows that it should. Also, there's no recording of this conduct in the xlogfile.

The below solution appears to fix both issues at once:

src/topten.c around line 424, add these lines:

`    if (!u.uconduct.elbereth)`
        `e |= 1L << 12;`

right beneath     
 `if (!num_genocides())`
         `e |= 1L << 11;`

I've tested this briefly and so far it works - you can see how many times you've engraved Elbereth, and it leaves a distinct conduct code in the xlogfile.

**Comment by NullCGT** [comment]
Thank you! I just added the code and tested it and it works great. Pushed the code.
