### ISSUE TITLE
Grass and ice tiles prevent running/rushing in rooms (G/g commands)

### ISSUE THREAD

**Issue by transcendreamer** [NullCGT/SpliceHack#160]
Many rooms now have grass so it hinders passing trough (character stops before stepping on grass) and forces to do more keypresses. Is this done by design or a bug?

**Comment by RojjaCebolla** [comment]
Anyone wanna PR a port of this? https://github.com/copperwater/xNetHack/commit/49ff2165

(i can get to it sometime later)
