### ISSUE TITLE
Maybe replace (or supplement) "#define UNIQDEATHS" with date/time based trigger for the month of June?

### ISSUE THREAD

**Issue by RojjaCebolla** [NullCGT/SpliceHack#166]
Automation is cool, and Nethack seems to be a very date/time-aware program.

See also: https://github.com/NullCGT/SpliceHack/commit/0bb42d1f85f7392fc02f58af08f7bda93614728a
Further enhancement: inform players about Junethack using welcome/load/save messages?

**Comment by RikerW** [comment]
See also https://github.com/Chris-plus-alphanumericgibberish/dNAO/commit/1b7604e12578d1887f2ae2fa7a39fa95d068c5d8, it's trivial to make a quick `is_june` function and then just call that in the right areas.  Could probably totally abandon `#define UNIQDEATHS` and just force all games ending in June to use 'killed by'. Might also be nice to add an rcfile option to use the default 'killed by' for every game on the offchance it's useful or desired later.
