### ISSUE TITLE
more issues with Elbereth conduct

### ISSUE THREAD

**Issue by k21971** [NullCGT/SpliceHack#17]
Noticing some odd behavior with the Elbereth conduct - its inconsistent.
1) issuing #conduct at the start, it will always show that you haven't engraved Elbereth if you haven't. so far so good
2) but if you do engrave it and then do #conduct afterwards, either it will show you how many times you've engraved it (good) or it doesn't show anything at all (not good). 
3) also - I engraved Elbereth with all lowercase letters and it scared a monster but doing #conduct afterwards showed that I hadn't engraved Elbereth yet. It's looking for uppercase E at the beginning I think.

I'm not sure how to fix this one.

**Comment by k21971** [comment]
Changing
`if (!in_mklev && !strcmp(s, "Elbereth")) {`

to
`if (!in_mklev && !strcmpi(s, "Elbereth")) {`

appears to resolve the upper/lower case issue.

**Comment by NullCGT** [comment]
I used your code to fix the case problem in 2cfb6576d5f86acdeac029277d97240218dd3c78. The inconsistent appearance might be due to a check I had for wizard mode, but I'll look into it more.

**Comment by k21971** [comment]
Ok great. Just FYI, I'm working on putting this into a server version of 3.6.1 (vanilla), it exhibits the same behavior there as well.

**Comment by NullCGT** [comment]
Cool! I'll see if I can recreate the inconsistency. It might be because it only increments if Elbereth is engraved successfully, or maybe the wizard check was being weird.

**Comment by NullCGT** [comment]
I've done some testing, and I haven't been able to duplicate the inconsistency issue in #conduct. I think the change to strcmpi and removal of the check for wizard mode may have fixed things.

**Comment by k21971** [comment]
I agree. I saw your commit from earlier today and tested it also. It appears to be reliable now.
