### ISSUE TITLE
Watery mkchasm levels: shops, grass

### ISSUE THREAD

**Issue by RojjaCebolla** [NullCGT/SpliceHack#170]
![image](https://user-images.githubusercontent.com/62170514/135110460-45fbd060-d171-4e0a-b2fe-600e7175d0b4.png)
An incredibly minor thing i've noticed is that grass never grows on spaces that are ex-wall. Wouldn't be worth an issue.

However, the shops with ex-wall terrain feel like Maybe A Bug. Are they intended and acceptable? When you walk onto the ex-wall, the shopkeeper warns you, asking you to pay before leaving. And if you keep going the Kops are summoned, but it's unusual to be able to walk out like this.

Then again, dwarves in minetown knock out shop walls all the time. Maybe it's fine?

**Comment by NullCGT** [comment]
I intended for there to be some weirdness in shop generation, so I think this is more of a quirk than a bug. It's definitely a little funny.
