### ISSUE TITLE
Named levels generation

### ISSUE THREAD

**Issue by transcendreamer** [NullCGT/SpliceHack#171]
This is a minor question about meaningful level names: for example now reached _**The Tranquil Pool**_ but I don't see any pool here... Are these names just random?

**Comment by RojjaCebolla** [comment]
Pool should definitely signify one or more fountains on the level. Maybe one's in a room behind a hidden door?

**Comment by transcendreamer** [comment]
Yes, there was a fountain `{` but not pool `}` - and looking at the level name I was expecting find something more thematically connected to a large pond/basin/reservoir not just one random fountain (for example dnethack has sunless see and this is a special named level) I understand this is quite minor issue and just wonder if I missed something or maybe this is reserved for future?

**Comment by transcendreamer** [comment]
Now I was looking into the dungeon.c code and I see it is generated as a combination of words related to dungeon objects and places... but the question is whether that named object/place is somehow different from random? - am I supposed to do something with that named fountain?

**Comment by RojjaCebolla** [comment]
Nope, it's just flavor!  I'll make sure the changelog is clearer about this.

**Comment by transcendreamer** [comment]
OK, thanks! Sorry for bothering with naïve questions ^-)
