### ISSUE TITLE
Infernals should know the True Names of demon lords

### ISSUE THREAD

**Issue by RojjaCebolla** [NullCGT/SpliceHack#179]
Just like how pirates and samurai rename certain items.

So, if playing an infernal, the demon lords' names are changed to 'Lex, Old Mo, Zuggy, Bubs, Demo, et cetera.

**Comment by NullCGT** [comment]
I'm a bit confused. Aren't the demon lords already referred to by their true names? The name of asmodeus is asmodeus, for example.

**Comment by RojjaCebolla** [comment]
It would be a jokey thing; the idea is that infernals would see a friendly nickname for each demon lord, instead of those lords' full names. Playing on the idea that infernals are "familiar" with all demons.
