### ISSUE TITLE
Dungeon overview incorrectly reporting shops

### ISSUE THREAD

**Issue by k21971** [NullCGT/SpliceHack#18]
See this screenshot - https://www.hardfought.org/phpBB3/gallery/image/2487/source

It did correctly label the delicatessen on dlvl 3. The shop here on dlvl 2 is not a health food store, but an archery shop instead.

**Comment by NullCGT** [comment]
Got it. This should be something fairly simple that I either missed or mistyped somewhere. I'll try to fix it, but I'm going to prioritize the two most critical bugs first (knives shooting poison gas and segfaults on restores with unpaid items).

**Comment by NullCGT** [comment]
As I suspected, I messed up a switch statement. This should be fixed by 619ebe65d71d592fafbeb5cb96ce867af7143d26.
