### ISSUE TITLE
pet ogre mage heals peacefuls

### ISSUE THREAD

**Issue by mobi-leuser** [NullCGT/SpliceHack#188]
My pet heals peacefuls it attacks:

_The invisible ogre mage misses the wombat.
The invisible ogre mage utters a complex chant.
The wombat looks better.  The invisible ogre mage hits the wombat._

I'd rather it only heal my other pets (and me)

**Comment by mobi-leuser** [comment]
OK, it actually heals pets too already:

_The mud elemental of Camaxtli looks better._

**Comment by RojjaCebolla** [comment]
fixed in afff774 , and maybe should be backported if this character of yours still lives
