### ISSUE TITLE
patchlevel tweak

### ISSUE THREAD

**Issue by k21971** [NullCGT/SpliceHack#22]
Just pulled down version 0.3, had a look in includes/patchlevel.h - I think you forgot to edit the patchlevel define, it's still as this:

`#define PATCHLEVEL 1`

Which would effectively make this build 0.3.1. Easy enough fix, I changed it to 0 before building. If you actually meant 0.3.1, please advise.

**Comment by NullCGT** [comment]
Sorry about that, it was definitely supposed to be 0.3.0.
