### ISSUE TITLE
Bug: Tourist entered wielding an uncursed tin opener that was welded to his hand

### ISSUE THREAD

**Issue by Celefoombor** [NullCGT/SpliceHack#233]
**Describe the bug**
I entered the dungeon as a tourist and started with a tin opener. The tin opener was uncursed but when I tried to unwield it, it was welded to my hand.

**To Reproduce**
I don't know if this is only for tourists who start with tin openers or not.

**Screenshots**
<img width="938" alt="Screenshot 2022-02-22 110118" src="https://user-images.githubusercontent.com/97325614/155170841-acb68dd2-59fb-4557-8bd1-abd3680efbc0.png">

I was playing on Hardfought, username Celefoombor.

**Comment by entrez** [comment]
Sounds like the same issue as #230, which has been closed already -- maybe the fix hasn't made it to Hardfought yet?
