### ISSUE TITLE
YANI: make the afraid status let you lose control of your movements only some of the time

### ISSUE THREAD

**Issue by mobi-leuser** [NullCGT/SpliceHack#238]
When you suffer from the afraid status you lose all control of your movements, which is extremely dire if you don't happen to have booze. Please make it so that you only lose control some of the time (like a more severe form of confusion) so that you have a chance to escape. (I can imagine that being afraid you won't be able to hit the dragon)

**Comment by NullCGT** [comment]
Good idea. Changed in 1.2.0.
