### ISSUE TITLE
Infernals should not spawn with anything made of silver, nor while sacrificing should their deity grant them any artifact made of silver. 

### ISSUE THREAD

**Issue by k21971** [NullCGT/SpliceHack#29]

**Comment by k21971** [comment]
Completely defeats the purpose. As an infernal wizard, I've spawned several times with rings in inventory made of silver - can't use them. Received weresbane a couple times as well sacrificing on a co-aligned altar. You see the point i'm making ;)

**Comment by NullCGT** [comment]
Absolutely agree that this is dumb, and totally unintentional difficulty. I pushed a temporary fix that changes all silver items in the initial inventory to iron. Doing a comprehensive fix is going to be more complicated.
