### ISSUE TITLE
Program in disorder (will-o'-wispfusion elemental)

### ISSUE THREAD

**Issue by k21971** [NullCGT/SpliceHack#30]
Got this message after being engulfed by a will-o'-wispfusion elemental:

The sleep ray rips into the will-o'-the-wispfusion elemental.
You hack the will-o'-the-wispfusion elemental.
The magic-absorbing blade scares the will-o'-the-wispfusion elemental!
Swallower has no engulfing attack?
Program in disorder!  (Saving and reloading may fix this problem.)
The immobile will-o'-the-wispfusion elemental seems to flinch.

Still able to continue playing after the fact.

**Comment by NullCGT** [comment]
Good catch. Fixed with commit ff917043.
