### ISSUE TITLE
Crash when swallowed by monster while riding steed

### ISSUE THREAD

**Issue by k21971** [NullCGT/SpliceHack#32]
Here's the coredump:

Core was generated by `/splicehack-0.5.1/splicehack -u k2'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f0ac3be7428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007f0ac3be7428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f0ac3be902a in __GI_abort () at abort.c:89
#2  0x00000000004940a2 in NH_abort () at end.c:212
#3  0x00000000004940c1 in panictrace_handler (sig_unused=<optimized out>) at end.c:139
#4  <signal handler called>
#5  0x00000000004ac46f in domove () at hack.c:1379
#6  0x000000000044c03b in rhack (cmd=0x88d360 <in_line> "2", cmd@entry=0x0) at cmd.c:4291
#7  0x0000000000421bbd in moveloop (resuming=<optimized out>) at allmain.c:476
#8  0x00000000005d31df in main (argc=3, argv=0x7ffca2b22588) at ../sys/unix/unixmain.c:342

I was playing a Dragonmaster, riding my dragon, and was swallowed by an air elemental. Crash did not happen immediately, was being pummeled by debris and was fighting back when crash occurred.

**Comment by k21971** [comment]
This happened again while being swallowed by a trapper (was not riding steed while inside trapper).

**Comment by NullCGT** [comment]
Probably more amalgamation and bad clone code causing swallowing to break. I'll take a look as soon as I get some free time.

**Comment by NullCGT** [comment]
Fixed with commit c6bfba2ac68429ea49cde03fc34a93b7756e9e20. This also fixes a related bug where dragons attempted to get their masters unstuck but failed.
