### ISSUE TITLE
Please add this commit

### ISSUE THREAD

**Issue by k21971** [NullCGT/SpliceHack#33]
https://github.com/tnnt-devteam/tnnt/commit/0b8d2e464843eb23a062e133f5fb0b2c6ec4b53b

This prevents the 'unknown command' spam from being displayed on dumplogs.

**Comment by copperwater** [comment]
Doesn't SpliceHack pull from 3.6.2-hdf anyway so it'd get this commit from there?

**Comment by NullCGT** [comment]
Wasn't I the one who originally wrote this?

**Comment by NullCGT** [comment]
Huh, it was not in my code. Added in 77aa50fcb2511cfafee3b390c541276a11ca6df5. Thank you, K2!
