### ISSUE TITLE
Infernal and hungerless regeneration.

### ISSUE THREAD

**Issue by tempestnano** [NullCGT/SpliceHack#34]
Version: b634fe93386bf7d4769f8ab1efe671c332a90ce7
Tested on hardfought.org and for confirmation used wizard mode when compiled from source.

The infernal's regeneration increases hunger the same amount as a ring of regeneration. I tested this in wizard mode by clocking the turns from hungry to weak for a level 4 infernal and a human wearing a ring of regeneration.

**Comment by NullCGT** [comment]
Fixed with commit c46c73a1bb6219c1d79acbda99c973006d65e3cd on new repository.
