### ISSUE TITLE
End-of-game reasons shifted, resulting in easy ascensions

### ISSUE THREAD

**Issue by AmyBSOD** [NullCGT/SpliceHack#38]
Due to some error with the end-of-game reasons, e.g. done(ESCAPED), it is possible to easily get a game to count as an ascension even if it really wasn't, which resulted in Splicehack being temporarily banned from the public server until you get this fixed: these are the observations I made.
- If you escape the dungeon via the upstair you start the game on, the xlogfile reports it as "ascended", so you can very easily get turn 1 ascensions that also appear in the scoreboard (this is why the variant got banned).
- If you use the #quit command, the xlogfile reports it as "escaped".
- If you genocide yourself, the xlogfile reports it as "panicked".
Couldn't easily reproduce the others (poisoned, burned, choked, drowned and whatever other done() reasons there are) but I'd not be surprised at all if they were similarly bugged, i.e. shifted by one in the internal list. In fact, actually ascending the game would probably not count as an ascension, and since ASCENDED is the last entry in the array, it could even result in the game trying to call an element outside of the array and segfault when you would have ascended!

Please get on the #hardfought IRC ASAP, the server administrators would probably want to talk to you so we can figure out how to fix this bug, and then they'll probably re-enable Splicehack! :)

**Comment by k21971** [comment]
I wouldn't use the word 'banned' - it's disabled until a fix is in place. A couple players discovered you could ascend in one turn and started spamming the livelog/xlogfile with ascensions. They showed up on the nethack scoreboard as well, skewing the results.

**Comment by NullCGT** [comment]
Fixed with commit c166f85e66494f7da3e1c2bfb70c1e08552b5e4f. Sorry about the mess.
