### ISSUE TITLE
Stun lock when wind-based monster blasts player into edge of map

### ISSUE THREAD

**Issue by Ardub23** [NullCGT/SpliceHack#42]
Issue #15 addresses the problem of being hurtled into a wall by a wind-based monster, which used to deprive the player of all movement for the remainder of their hurtle time. However, these monsters can still stun-lock the player on levels that extend to the very edge of the map. (Most levels have undiggable stone preventing access to the map edge, but not all.) When the player hurtles into the edge of the map, they get the message "You feel the spirits holding you back" and remain unable to move.

The stun lock is seen in [this ttyrec](https://github.com/NullCGT/SpliceHack/files/3821251/2019-11-05.17_45_35.ttyrec.gz), lasting from turn 35998 to turn 36032 (34 turns) and causing a great deal of unpleasantry.

Though I'm no expert on NetHack's code, I see that the commit which fixed Issue #15 added `unmul((char *) 0);` before several of the `return FALSE` statements in `hurtle_step` (from dothrow.c). The return statement associated with "spirits holding you back" was not one of them. `hurtle_step` apparently returns false whenever hurtling is blocked, so it seems that `unmul` ought to be called before all `return FALSE` statements in `hurtle_step` to prevent all such stun locks.

**Comment by NullCGT** [comment]
Thanks for the report, and sorry it took so long to get to it. That sounds incredibly annoying.

Fixed via 8c3cc071dac84bd906d5a7a8d22661d2ca907353.
