### ISSUE TITLE
Vampire player race is subject to stoning when attacking petrifying monsters

### ISSUE THREAD

**Issue by enetics-secker** [NullCGT/SpliceHack#43]
The Slash'em and UnNethack player race Vampire is smart enough to avoid biting petrifying creatures thus killing themselves:

in uhitm.c - /* [ALI] Vampires are also smart. They avoid biting monsters if doing so would be fatal */

Doesn't seem to be working in Splicehack.

**Comment by NullCGT** [comment]
Thank you for the report! I'll address it as soon as I am able.

**Comment by NullCGT** [comment]
Fixed via 9db784b88ef3249f1a194854bdbf64fc23db449c.
