### ISSUE TITLE
Can't go down holes while flying (Vampire)

### ISSUE THREAD

**Issue by enetics-secker** [NullCGT/SpliceHack#52]
Either player race vampire, polymorphed as a vampire or other flying race, or riding a flying steed one cannot descend through a hole or trap door.  Pressing ">" to descend shows the message:

"There's a gaping hole under you!  You don't fall in."

**Comment by NullCGT** [comment]
I think that this has to do with the ordering of functions and use of `dotrap` in `do.c`, which is odd, since I haven't touched that. This does not occur in vanilla NetHack, correct?

**Comment by k21971** [comment]
I believe this has something to do with a recent commit to vanilla NetHack. I get this exact same thing in EvilHack, and just tested this with a clean build of NetHack 3.6.3 post-release, it's there also.

This is a vanilla bug.

**Comment by NullCGT** [comment]
Sounds good. I'll wait for the vanilla hotfix and pull it in here.

**Comment by enetics-secker** [comment]
I removed "|| Flying" from line 500 of trap.c and I can descend again. It likely breaks something else, though.

**Comment by k21971** [comment]
enetics-secker, devteam addressed your pull request, provided a fix for this on the official nethack repo. see commit edd9d5b.

**Comment by enetics-secker** [comment]
addressed by edd9d5b8103e69de47037eb88e73473084f1379a
