### ISSUE TITLE
Orc captains do not use orc tribe naming conventions in orctown.

### ISSUE THREAD

**Issue by NullCGT** [NullCGT/SpliceHack#54]

**Comment by copperwater** [comment]
Is this splice-specific or is it a vanilla bug?

**Comment by NullCGT** [comment]
Seems to be splice-specific, although since opening this issue, I have been unable to reproduce this bug, and have encountered named orc captains in orctown.

**Comment by NullCGT** [comment]
Closing this out, as I believe that if this issue truly exists, it has been fixed by f0c88a3c9e81a0e67d93e04b3c6aa4d9b1671e88.
