### ISSUE TITLE
Shambling Horror randomized stats are forever discarded on save/reload

### ISSUE THREAD

**Issue by NullCGT** [NullCGT/SpliceHack#59]

**Comment by k21971** [comment]
I attempted to resolve this awhile back with evilhack, no luck. Looking forward to what you come up with.

**Comment by NullCGT** [comment]
Glad to know it's not just me. My gut is telling me that there isn't going to be a simple or easy fix for this issue, unfortunately.

**Comment by NullCGT** [comment]
The mons[] array is never saved, and shambling horrors stats are only initialized at the beginning of the game.
There are two possible solutions to this:

1. Add shambling horror statistics to the save file.

2. Remove shambling horrors in favor of some other sort of monster.

**Comment by k21971** [comment]
Option 2 isn't really an option. Time to bug bhaak about this... and ask aosdict as well, he mentioned something the other day about 'if you made a separate RNG for rolling up shambling horror stats and seeded it with ubirthday, you wouldn't have to add anything else to the save file'

**Comment by NullCGT** [comment]
Aosdict's idea is really good. Seeding an RNG function with ubirthday would solve things without any sort of savefile bloat or in-game effect.

**Comment by k21971** [comment]
https://github.com/k21971/EvilHack/commit/53557949b390509d32b73d6a0ca5395b9085ca04

\o/

**Comment by NullCGT** [comment]
\o/

Nice!

I'll be taking this. Yoink!
