### ISSUE TITLE
Compile a windows binary

### ISSUE THREAD

**Issue by blightor** [NullCGT/SpliceHack#64]
As requested, raising an issue to cover creating a windows binary release for SpliceHack!

And also please include a monster named blightor ;)

**Comment by NullCGT** [comment]
I haven't forgotten about this. I'm currently undertaking the massive project updating Splice's codebase to match 3.7.0 standards, and waiting for the next major version bump of Splice to do a release.

**Comment by blightor** [comment]
Love your work!

**Comment by Valo616** [comment]
I'd also greatly appreciate a Windows release!

**Comment by NullCGT** [comment]
Hey all, just wanted to say that SpliceHack 0.7.1 now has a windows binary, with both ascii and tiled options! You can download it from the releases page: https://github.com/NullCGT/SpliceHack/releases/tag/Spl-0.7.1.

As this is the first version of SpliceHack on windows, bugs are bound to exist. One known one is that in the tiles build,  lit squares are rendered as black. Despite this, the build is completely playable in its present state.

Sorry for how long this took to put together! I hope you enjoy.

**Comment by blightor** [comment]
> Hey all, just wanted to say that SpliceHack 0.7.1 now has a windows binary, with both ascii and tiled options! You can download it from the releases page: https://github.com/NullCGT/SpliceHack/releases/tag/Spl-0.7.1.
> 
> As this is the first version of SpliceHack on windows, bugs are bound to exist. One known one is that in the tiles build, lit squares are rendered as black. Despite this, the build is completely playable in its present state.
> 
> Sorry for how long this took to put together! I hope you enjoy.

Well done and thankyou!

**Comment by NullCGT** [comment]
No problem!

It definitely wasn't a one person effort. K2 has helped so much in getting it running :)
