### ISSUE TITLE
Monsters switching back and forth between melee and ranged weapon in a loop at a certain range

### ISSUE THREAD

**Issue by k21971** [NullCGT/SpliceHack#68]
I have a partial 'fix' here - https://github.com/k21971/EvilHack/commit/a0cae1ec2687c2fc742bd1bb61e1b9eb6e90862e - read the commit notes for details.

**Comment by NullCGT** [comment]
Implemented EvilHack fix in 88ed06aa9194ebca773a1cb7227f1ea1b20c452e.
