### ISSUE TITLE
impossible() when viewing encyclopedia for unwriteable scrolls and non-spell books

### ISSUE THREAD

**Issue by Ardub23** [NullCGT/SpliceHack#69]
`add_obj_info` in pager.c does not include special cases for special scrolls and spellbooks.

For the unwriteable scrolls of knowledge and blank paper, the call to `ink_cost` in write.c leads to `impossible` because it assumes the checks in `dowrite` were already made. (Also, `dowrite` checks for the scroll of knowledge after looking for an ink cost, when it should do it before like all the other unwriteable documents.)

For the novel, spellbook of blank paper, and Book of the Dead, the call to `spelltypemnemonic` in spell.c leads to `impossible` because there is no spell for these books. Also, it incorrectly displays an ink cost for the unwriteable blank paper and Book of the Dead.

xNetHack partially fixes this by having `add_obj_info` special-case the blank scroll and spellbook to display "Can be written on." rather than an ink cost, and it skips the level, school, and direction for the spellbook of blank paper. Importing these special cases should work fine, though additional ones need to be added for the novel, scroll of knowledge, and Book of the Dead.

**Comment by NullCGT** [comment]
Thank you for the report. Resolved via commit a1fc6bebb67a39113906be7e3ab5027d9575ea28. Commit will be in development, and go live with the next major update.
