### ISSUE TITLE
Monster can mount dead steed, leading to crash; recovery fails

### ISSUE THREAD

**Issue by Ardub23** [NullCGT/SpliceHack#74]
I was in a room with a nurse and a jabberwock. I went for the jabberwock first and got these messages in succession:
```
The black blade draws the life from the jabberwock!
Ye kill the jabberwock!
The nurse clambers onto the jabberwock!
```
Farlooking at the nurse revealed it to be a "nurse, riding a jabberwock". I tried saving and reloading (which admittedly was unwise—I should've let the checkpoint save work instead). On reload I was greeted with a "Cannot find monster steed" error message and booted back to the server menu. The next try gave me the option to try to recover the save file, which failed (whoops).

My guess as to the cause of the initial problem is that mount_up() is called in movemon() (from mon.c) before dmonsfree() removes dead monsters, while the code in mount_up() doesn't account for the fact that dead monsters may still be present. If this is correct, then adding a check for HP >= 1 to the if statement on [steed.c line 77](https://github.com/NullCGT/SpliceHack/blob/Master/src/steed.c#L77) should work, though it doesn't address whatever it is that went wrong when restmonsteeds() tried to recover from it.

I have the ttyrecs, in case they might help troubleshoot the recovery failure. The nurse mounts the jabberwock at the end of [this one](https://github.com/NullCGT/SpliceHack/files/4665550/2020-05-21.22_37_03.ttyrec.gz); the attempt to reload the save is [here](2020-05-21.23_22_49.ttyrec.gz). (Looks like something in free_erid()? I don't understand the code there well enough to guess.)

**Comment by k21971** [comment]
Ardub23, your game is recovered. I've also made a backup of the initial backup before your last session, so if your game has become corrupt somehow and won't load, there's a chance it can still be salvaged, albeit X number of turns back.

AntiGulp, you had a non-recoverable crash as well (checkpoint was non-existent), it's been recovered from a prior save as well.

**Comment by NullCGT** [comment]
I added a check for DEADMONSTER(), since that's the standard macro for checking if the hit points of a monster indicate that it should be dead.

I also prevented monsters from jumping into holes if they're part of a rider/steed pair.

**Comment by Ardub23** [comment]
k21971, I tried to load SpliceHack just now and got the same "Cannot find monster steed" error as before.
[2020-05-23.00_49_26.ttyrec.gz](https://github.com/NullCGT/SpliceHack/files/4670906/2020-05-23.00_49_26.ttyrec.gz)

**Comment by k21971** [comment]
Ardub23, ok... I've recovered your game again, using the slightly older backup I mentioned earlier. SpliceHack has been updated just now with the most recent commits as of this post.

**Comment by Ardub23** [comment]
Now it just brings me to the start-of-game character creation.

**Comment by k21971** [comment]
My bad, I used 'Ardub23' instead of just 'Ardub' for your saved game filename. Try now.

**Comment by Ardub23** [comment]
I got "Cannot find monster steed" and crash to menu again.

**Comment by k21971** [comment]
Plan C - I've restored your game from the most recent daily backup. This will be quite a few turns back prior to when you experienced this crash. It appears the current save is corrupt. Either email me at admin@hardfought.org or connect to freenode irc and join #hardfought and let me know how it goes - we really shouldn't clutter up this issue with topics that are beyond its scope.
