### ISSUE TITLE
boiling potions didn't seem to harm me (in junethack)

### ISSUE THREAD

**Issue by RojjaCebolla** [NullCGT/SpliceHack#85]
hi there, during JNH i was dipping pots into furnaces to try for unique deaths. **exploding** potions killed me alright, but **boiling** potions didn't seem to damage me at all.  is that correct/intended behavior?  might be interesting if some potions boil and others explode, but only if that's trivialish to code...

 _i'd test locally, but upont launching `~/spl/install/lib/games/splicehackdir/splicehack` it's doing the "Unable to open SYSCF_FILE." thing and i didn't manage to sort it out by attempting to follow [this advice](https://old.reddit.com/r/nethack/comments/60mdyh/unable_to_open_syscf_file/)_

**Comment by NullCGT** [comment]
I haven't successfully duplicated this yet, but I'm still trying.

In regards to the "Unable to open SYSCF_FILE" error, do you have a file named "sysconf" in your splicehackdir?

**Comment by RojjaCebolla** [comment]
Thanks, probably not a big deal, reasonable play generally isn't going to involve intentionally boiling one's potions!

I haven't figured out for certain where my splicehackdir is, but i can try distributing to some likely spots (the git/splice/ directory, /home/user/, home/user/splicehack, etcetera

**Comment by RojjaCebolla** [comment]
ok, yep, i have an ~/spl/install/lib/games/splicehackdir/sysconf and it even has words in it

maybe if you have time i can pick your brain on IRC!

**Comment by NullCGT** [comment]
Closing this out for now. Will reopen if issue reoccurs.
