### ISSUE TITLE
quick fixes from XNH

### ISSUE THREAD

**Issue by RojjaCebolla** [NullCGT/SpliceHack#90]
i'm grabbin some of the simple fixes and QoL stuff from xnethack. https://github.com/NullCGT/SpliceHack/pull/89

@transcendreamer and @Ardub23 and other folx around here, feel free to recommend any other obvious good commits.

**Comment by RojjaCebolla** [comment]
it looks like XNH has done a lot of stuff with object materials, including ensuring that elves aren't harmed when they (a)pply an iron tool, such as a key.  Intriguingly right now, if i walk into a locked door, the _autounlock_ does not hurt, but if i apply a key, it does hurt.  Perhaps grab most or all of XNH's object material fixes?  https://github.com/copperwater/xNetHack/commit/c6c68df1f83a098904c0cb4580a7048c05969704

![image](https://user-images.githubusercontent.com/62170514/86886540-203a3f80-c0c5-11ea-85c6-9ab8c70e20b7.png)

(alternate thought: object materials seems to be a flavor-first mechanic - i'm not sure that it leads to interesting gameplay - is it worth the hassle of maintaining and fixing?)

**Comment by copperwater** [comment]
Gameplay arguments in favor of the object materials system:
1. It provides a big increase to the complexity of the player's gear choices without adding any new objects.
2. Without it, every object is the same as every other object of its type except for easily modifiable factors such as erosion and enchantment, so once you have one, others are likely useless.
3. From the above, it extends the length of time in the game in which you can "upgrade" your gear - maybe you get a regular key early on, but then find a mithril one later and are happy that you got something lighter and non-rustable. In vanilla you would just ignore the second key.
4. It offers more interesting gear choices. Do you go with the wooden shield, which is lighter and won't hinder your spellcasting as much, or go defensive with the iron shield for more AC? (In fact, this particular choice exists in vanilla - but the shields have to exist as separate objects for it to work.)
5. It can make races more varied. Granted, in xnethack this only applies to elves at the moment, but splice and evilhack add in additional race material interactions. Will you still play an elven wizard for the high Intelligence if it means the Mines will be especially dangerous?
6. Building off the above, combat becomes more varied than what vanilla has with silver-hating monsters. If you're an infernal and you see "The goblin wields a silver dagger!", you might think twice before charging in to melee it. If you see a squad of elves approaching, it might be time to put away your mithril weapon so you can take advantage of their vulnerability to iron.

**Comment by RojjaCebolla** [comment]
thanks for explainin!  most of my experiences with object materials have been in other variants, going "dammit, this thing is gold/silver/other-useless-material, it weighs a ton", or in this variant, taking damage from just trying to touch/use everything in the dungeon.  oh! there was also some time spent in DNH, using Unarmed but hoarding mithril/silver weapons that i thought i might wanna use, and then finding a lightsaber anyways so none of that hauling had mattered.  

i do like the idea of finding useful materials that are attached to relevant items, i probly just need to play more!
