### ISSUE TITLE
idea for a room: The Kitchen! (sorry)

### ISSUE THREAD

**Issue by RojjaCebolla** [NullCGT/SpliceHack#98]
So, i wanted to make a cool special room, but i was looking at [the nonsense](https://github.com/NullCGT/SpliceHack/blob/faa0126d10ff66c2cf23e26be0af20108758a372/src/mkroom.c#L337) in mkroom.c and mklev.c and just... finding all those impenetrable abbreviations to be completely demoralizing.

SO i'm here, like a scrub, posting a YANI instead. Sigh. Sorry!

###             You("enter a utilitarian kitchen!");

- It has a sink and a furnace and a dented pot.  
- It has a 70% chance of a tin opener. 
- An independent 20% chance of a tinning kit. 
- Some potions of oil and fruit juice, 
- and sometimes also the potion with the appearance "soupy".
- Maybe occasional cheese and cake and pineapples, 
-- maybe that stuff should be kept in an icebox?

It's a long, narrow, lit room.

In the changelog, you mention "the new level coder", maybe i should try using that?  But if that's for .des files (which are relatively easy!) then it probably doesn't help, cuz what i wanna make is a _room_ that shows up on normal floors, not a whole new floor.  

(...though a kitchen could certainly make sense as an addition to the Banquet Hall, or the Wine Cellar...)

**Comment by copperwater** [comment]
This sounds like it would be better implemented as a themed room than a special room.

Pros: 
- It can appear alongside other themed rooms and special rooms in the Dungeons without the 1-per-level constraint or "stealing frequency" from other special rooms.
- Theme room dimensions can be controlled easily in Lua; currently no code exists to control special room dimensions and it would have to be done painfully with a bunch of special casing in C
- Rooms with a bunch of single things in them fits a themed room more than a special room, which tend to use a "uniform probability per each square" approach.

Cons:
- Themed rooms can't be made to appear in special levels. I mean, you could just copy and paste the Lua code, but yuck, code duplication. Hmm, I wonder if there's any way to put a kitchen generator function into its own lua file and then have both themerms.lua and special level lua files include and execute it.
- Themed rooms currently can't have entry messages, as there is no data stored in the room to designate them as a certain type. Though I have had some ideas on how to do this.

Suggestion:
- The kitchen should also have some tins.

(Side note: Splice is no longer using des files, and themed rooms use "the new level coder" just like special levels, without being special levels. It should be fairly easy to add a new themed room to themerms.lua with a basic grasp of Lua.)

**Comment by RojjaCebolla** [comment]
That all makes sense, thanks!

I had the impression that "the new level coder" was a GUI of some kind but i'm getting the feeling it's just a different way for the game to generate levels?

**Comment by copperwater** [comment]
The new level coder is the use of Lua script to generate levels and themed rooms instead of the previous domain-specific language des, which required its own custom compiler, syntax, was comparatively difficult to learn and use, and was notoriously inflexible. It was also declarative instead of procedural.

You can see the use of Lua scripts for level generation all over the dat folder.

**Comment by RojjaCebolla** [comment]
i'll make a PR if i figger this out ^_^
